"""empty message

Revision ID: 07313f348c49
Revises: 8b5f3b2cc855
Create Date: 2023-05-22 00:49:19.836780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07313f348c49'
down_revision = '8b5f3b2cc855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
