"""empty message

Revision ID: 8b5f3b2cc855
Revises: 53b7d7960ece
Create Date: 2023-05-21 23:51:45.599337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5f3b2cc855'
down_revision = '53b7d7960ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_show_artist_name', type_='foreignkey')
        batch_op.drop_constraint('Show_venue_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'])
        batch_op.drop_column('venue_name')
        batch_op.drop_column('artist_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Show_venue_name_fkey', 'Venue', ['venue_name'], ['name'])
        batch_op.create_foreign_key('fk_show_artist_name', 'Artist', ['artist_name'], ['name'])
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###
