"""empty message

Revision ID: b7a324e709d3
Revises: a905ea37b0ec
Create Date: 2023-05-21 15:44:13.747465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a324e709d3'
down_revision = 'a905ea37b0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        # batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=True))
        # batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=True))
        batch_op.alter_column('genres', 
                              existing_type=sa.String(length=120), 
                              type_=sa.ARRAY(sa.String(length=120)), nullable=False)

    # with op.batch_alter_table('Show', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('venue_name', sa.String(), nullable=False))
    #     batch_op.drop_constraint('fk_show_venue_name', type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'Venue', ['venue_name'], ['name'])
    #     batch_op.drop_column('venue')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('genres', 
                              existing_type=sa.String(length=120), 
                              type_=sa.ARRAY(sa.String(length=120)), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_show_venue_name', 'Venue', ['venue'], ['name'])
        batch_op.drop_column('venue_name')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_venue')
        batch_op.drop_column('website')

    # ### end Alembic commands ###
